version: "3"
services:

  flyway:
    container_name: flyway-container
    depends_on:
      - mysql
    build: .
    image: flyway-image:0.9
    environment:
      - PASSWORD=test
      - USER=root
      - DSN=jdbc:mysql://mysql-container:3306/exemple

  mysql:
    container_name: mysql-container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: exemple
    ports:
      - "3306"


